# Generated by Django 4.2.15 on 2024-09-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_of_payment',
            field=models.DateTimeField(verbose_name='Дата оплаты'),
        ),
    ]
