# Generated by Django 4.2.15 on 2024-09-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_payment_options_alter_payment_date_of_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payed_course',
            new_name='payed_course_or_lesson',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payed_lesson',
        ),
    ]
