# Generated by Django 4.2.15 on 2024-09-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_payed_course_payment_payed_course_or_lesson_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
