# Generated by Django 4.2.15 on 2024-09-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_payment_type_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type_of_payment',
            field=models.CharField(verbose_name='Способ оплаты: наличные или перевод на счет.'),
        ),
    ]
