# Generated by Django 4.2.15 on 2024-09-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_payment_type_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_amount',
            field=models.FloatField(verbose_name='Cумма оплаты'),
        ),
    ]
