# Generated by Django 4.2.15 on 2024-09-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_payment_type_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cумма оплаты'),
        ),
    ]
