# Generated by Django 4.2.15 on 2024-09-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_payed_course_or_lesson_payment_payed_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type_of_payment',
            field=models.CharField(default=False, verbose_name='Способ оплаты: наличные или перевод на счет.'),
        ),
    ]
