# Generated by Django 4.2.15 on 2024-09-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_payment_type_of_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payed_course',
            new_name='payed_course_or_lesson',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payed_lesson',
        ),
        migrations.AlterField(
            model_name='payment',
            name='type_of_payment',
            field=models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод на счет')], verbose_name='Способ оплаты: наличные или перевод на счет.'),
        ),
    ]
