# Generated by Django 4.2.15 on 2024-09-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_course_video_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='courses/photo', verbose_name='Превью'),
        ),
    ]
