# Generated by Django 4.2.15 on 2024-09-09 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0009_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='course_subscription',
            new_name='subscription',
        ),
    ]
