# Generated by Django 4.2.15 on 2024-09-09 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0010_rename_course_subscription_subscription_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='subscription',
            new_name='course',
        ),
    ]
